manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      # Zephyr v4.4.0
      revision: 4f50f0ba8905f27b2f60123d0ee0934fda6fe134
      west-commands: scripts/west-commands.yml
  self:
    path: corejack
